addresses:
    # Address of the $BOND token
    bond: ""
    # Exclude transfers from these addresses when computing holders of BOND
    exclude-transfers: []
api:
    # Enable development cors for HTTP API
    dev-cors: false
    # Allowed host for HTTP API dev cors
    dev-cors-host: ""
    # HTTP API port
    port: "3001"
db:
    # Database name
    dbname: name
    # Database host
    host: localhost
    # Database password (also allowed via PG_PASSWORD env)
    password: ""
    # Database port
    port: "5432"
    # Database sslmode
    sslmode: disable
    # Database user (also allowed via PG_USER env)
    user: ""
# Display debug messages
logging: '*=info'
metrics:
    # Port on which to serve Prometheus metrics
    port: 9909
