addresses:
    # Address of the $BOND token
    bond: ""
    # Exclude transfers from these addresses when computing holders of BOND
    exclude-transfers: []
api:
    # Enable development cors for HTTP API
    dev-cors: false
    # Allowed host for HTTP API dev cors
    dev-cors-host: ""
    # HTTP API port
    port: "3001"
db:
    # Auto run database migrations
    automigrate: true
    # Database name
    dbname: simulator
    # Database host
    host: localhost
    # Database password
    password: password
    # Database port
    port: "5432"
    # Database sslmode
    sslmode: disable
    # Database user
    user: core
# Display debug messages
logging: ""
metrics:
    # Port on which to serve Prometheus metrics
    port: 9909
